/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package androidmobilegen;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dev
 */
public class Generador extends javax.swing.JFrame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dir = "/Users/dev/Desktop/iTest";
        File f = null;
        f = new File(dir.trim() + "/" + "MainActivity.java");
        FileWriter w;
        try {
            w = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);
           
            wr.println("package cl.disma.test;");

            wr.println("import androidx.appcompat.app.AppCompatActivity;");

            wr.println("import android.os.Bundle;");

            wr.println("public class MainActivity extends AppCompatActivity {");

            wr.println(" @Override");
            wr.println(" protected void onCreate(Bundle savedInstanceState) {");
            wr.println("super.onCreate(savedInstanceState);");
            wr.println(" setContentView(R.layout.activity_main);");
            wr.println("}");
            wr.println("}");

            

           
            wr.close();
            bw.close();
               JOptionPane.showMessageDialog(null, "Generado Java");

        } catch (IOException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        }

       
        
        File f1 = null;
        f1 = new File(dir.trim() + "/" + "activity_main.xml");
        FileWriter w1;
        try {
            w1 = new FileWriter(f1);
            BufferedWriter bw1 = new BufferedWriter(w1);
            PrintWriter wr1 = new PrintWriter(bw1);
           
           

            wr1.println("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            wr1.println("<androidx.constraintlayout.widget.ConstraintLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"");
            wr1.println("  xmlns:app=\"http://schemas.android.com/apk/res-auto\"");
            wr1.println("   xmlns:tools=\"http://schemas.android.com/tools\"");
            wr1.println("   android:layout_width=\"match_parent\"");
            wr1.println("   android:layout_height=\"match_parent\"");
            wr1.println("   tools:context=\".MainActivity\">");

            wr1.println("    <Button");
            wr1.println("        android:id=\"@+id/btnCrear\"");
            wr1.println("        android:layout_width=\"wrap_content\"");
            wr1.println("        android:layout_height=\"wrap_content\"");
            wr1.println("        android:layout_marginStart=\"98dp\"");
            wr1.println("        android:layout_marginLeft=\"98dp\"");
            wr1.println("        android:layout_marginTop=\"142dp\"");
            wr1.println("        android:text=\"Crear\"");
            wr1.println("        app:layout_constraintStart_toStartOf=\"parent\"");
            wr1.println("        app:layout_constraintTop_toTopOf=\"parent\" />");

            wr1.println("    <Button");
            wr1.println("        android:id=\"@+id/btnBuscar\"");
            wr1.println("        android:layout_width=\"wrap_content\"");
            wr1.println("        android:layout_height=\"wrap_content\"");
            wr1.println("        android:layout_marginStart=\"1dp\"");
            wr1.println("        android:layout_marginLeft=\"1dp\"");
            wr1.println("        android:layout_marginTop=\"45dp\"");
            wr1.println("        android:text=\"Buscar\"");
            wr1.println("        app:layout_constraintStart_toStartOf=\"@+id/btnCrear\"");
            wr1.println("        app:layout_constraintTop_toBottomOf=\"@+id/btnCrear\" />");

            wr1.println("    <Button");
            wr1.println("        android:id=\"@+id/btnSalir\"");
            wr1.println("        android:layout_width=\"wrap_content\"");
            wr1.println("        android:layout_height=\"wrap_content\"");
            wr1.println("        android:layout_marginTop=\"47dp\"");
            wr1.println("        android:layout_marginEnd=\"1dp\"");
            wr1.println("        android:layout_marginRight=\"1dp\"");
            wr1.println("        android:text=\"Salir\"");
            wr1.println("        app:layout_constraintEnd_toEndOf=\"@+id/btnBuscar\"");
            wr1.println("        app:layout_constraintTop_toBottomOf=\"@+id/btnBuscar\" />");
            wr1.println("</androidx.constraintlayout.widget.ConstraintLayout>");


           
            wr1.close();
            bw1.close();
               JOptionPane.showMessageDialog(null, "Generado XML");

        } catch (IOException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

     

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
